# Generated by Django 6.0.3 on 2026-03-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_fooditem_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': '食材', 'verbose_name_plural': '食材'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'レシピ', 'verbose_name_plural': 'レシピ'},
        ),
    ]
