# Generated by Django 6.0.3 on 2026-03-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_fooditem_options_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.IntegerField(choices=[(1, '青果'), (2, '魚/肉'), (3, '常温'), (4, '冷蔵'), (5, '主食'), (6, '冷凍'), (7, 'その他')]),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_kind', models.IntegerField(choices=[(0, '食材'), (1, '調味料')], default=0, verbose_name='材料区分')),
                ('amount_text', models.CharField(max_length=32, verbose_name='分量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.fooditem', verbose_name='食材')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='レシピ')),
            ],
            options={
                'verbose_name': 'レシピ材料',
                'verbose_name_plural': 'レシピ材料',
                'constraints': [models.UniqueConstraint(fields=('recipe', 'food_item'), name='unique_recipe_food_item')],
            },
        ),
    ]
