# Generated by Django 6.0.3 on 2026-03-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_user_alter_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.IntegerField(choices=[(1, '青果'), (2, '魚/肉'), (3, '常温'), (4, '冷蔵'), (5, '主食'), (6, '冷凍'), (7, 'その他')], verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredient_name',
            field=models.CharField(max_length=30, verbose_name='食材名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100, verbose_name='レシピ名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(verbose_name='作る量'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='手順番号')),
                ('instruction', models.TextField(verbose_name='手順内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='レシピ')),
            ],
            options={
                'verbose_name': '作り方',
                'verbose_name_plural': '作り方',
                'ordering': ['step_no'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'step_no'), name='unique_recipe_step_no')],
            },
        ),
    ]
