# Generated by Django 6.0.3 on 2026-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reference_url',
            field=models.URLField(blank=True, verbose_name='参照URL'),
        ),
    ]
