# Generated by Django 6.0.3 on 2026-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menu_category',
            field=models.IntegerField(blank=True, choices=[(1, '主食'), (2, '主菜'), (3, '副菜'), (4, '汁物')], null=True, verbose_name='カテゴリ'),
        ),
    ]
