# Generated by Django 6.0.3 on 2026-03-15 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_image_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='recipes.recipe', verbose_name='レシピ'),
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='献立日')),
                ('eat_out', models.BooleanField(default=False, verbose_name='外食')),
                ('deli', models.BooleanField(default=False, verbose_name='惣菜')),
                ('is_cooked', models.BooleanField(default=False, verbose_name='つくった')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '献立',
                'verbose_name_plural': '献立',
            },
        ),
        migrations.CreateModel(
            name='MenuSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('staple', '主食'), ('main', '主菜'), ('side', '副菜'), ('soup', '汁物')], max_length=10, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='recipes.menuday', verbose_name='献立')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='レシピ')),
            ],
            options={
                'verbose_name': '献立枠',
                'verbose_name_plural': '献立枠',
            },
        ),
        migrations.AddConstraint(
            model_name='menuday',
            constraint=models.UniqueConstraint(fields=('user', 'plan_date'), name='unique_user_plan_date'),
        ),
        migrations.AddConstraint(
            model_name='menuslot',
            constraint=models.UniqueConstraint(fields=('menu_day', 'meal_type'), name='unique_menu_day_meal_type'),
        ),
    ]
