# Generated by Django 6.0.3 on 2026-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_homefooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_type',
            field=models.IntegerField(choices=[(1, '食材'), (2, '調味料')], default=1, verbose_name='食材種別'),
        ),
    ]
