# Generated by Django 6.0.3 on 2026-04-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_fooditem_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient_kind',
        ),
    ]
