# Generated by Django 6.0.3 on 2026-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipeingredient_ingredient_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_type',
            field=models.IntegerField(choices=[(1, '食材'), (2, '調味料ほか')], default=1, verbose_name='食材種別'),
        ),
    ]
