# Generated by Django 6.0.3 on 2026-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_fooditem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='reading_kana',
            field=models.CharField(blank=True, max_length=50, verbose_name='よみがな'),
        ),
    ]
