# Generated by Django 6.0.3 on 2026-05-14 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_fooditem_reading_kana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='ingredient_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='食材名'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_type',
            field=models.IntegerField(choices=[(1, '食材'), (2, '調味料ほか')], default=0, verbose_name='食材種別'),
        ),
        migrations.CreateModel(
            name='TemporaryRecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_recipe_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
